회원가입
devsince2021/ms pull request #9
Opened 2023-09-15 09:14 UTC by sonnbeom

회원가입/ 비밀번호 암호화 필요.

2023-09-15 10:08 UTC, devsince2021 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
org.springframework.boot:spring-boot-starter-
이렇게 스프링-부프-스타터로 시작하는 라이브러리들은 모두가 아는 라이브러리일 경우가 많으니 주석을 안달아줘도 괜찮을 것 같고
조금 특별한 라이브러리를 추가할 때 주석을 달아주는것도 좋을 것 같습니다.

2023-09-15 10:34 UTC, devsince2021 requested changes
첫 커밋 축하드립니다 ㅋㅋㅋ @sonnbeom 

ExceptionHandling 파일의 코드는 수정을 하고 병합을 하는 것이 좋을 것 같습니다.
그 이외의 코멘트는 참고 삼아서 봐주시면 감사하겠습니다.

2023-09-15 10:34 UTC, devsince2021 commented on src/main/java/com/hypeboy/hypeBoard/controller/ExceptionHandlingController.java
전역 에러 컨트롤러 작성하신 것 너무 좋습니다!

마이너한 부분이지만 수정하면 좋을 것 같은 부분 몇가지 적어봅니다~
1. 메소드 이름과 인자의 변수명을 규칙성있게 적으면 좋을 것 같습니다.
```
public ModelAndView exceptionHandle(IllegalStateException ex)
public ModelAndView nosuchElementExcep(NoSuchElementException empty)
```
위 코드를 보면 메소드명에 하나는 handle이라는 이름을 쓰고 있고, 하나는 Excep이라는 이름을 쓰고 있습니다.
또 인자명에는 ex와 empty를 각각 사용하고 있습니다.
일관성있는 코드를 사용하면 유지보수와 가독성에 큰 도움을 줍니다~

2. 반복되는 코드 제거
두개의 메소드가 완전하게 동일한 코드를 가지고 있습니다.
코드 작성시에 반복을 최대한 피해야합니다. 
반복되는 부분을 줄여보기를 권해드립니다.

3. 필요한 주석인지 고민해보기
주석이 필요할 경우와 그렇지 않은 경우에 대해서 고민해보면 좋을 것 같습니다.

2023-09-15 10:34 UTC, devsince2021 commented on src/main/java/com/hypeboy/hypeBoard/controller/UserController.java
> +        User user = userService.toEntity(userDto);
'엔티티와 dto를 어느 레이어에서 변경할 것인가?' 에 대해서 오늘 종이에 V C S R D 이렇게 적어서 이야기를 나눴던 것으로 기억합니다. 
Service와 Repository 사이에서 진행할 계획이라고 해주셨던 것 같은데, C에서 하고 있는 상황인것 같습니다.

2023-09-15 10:34 UTC, devsince2021 commented on src/main/java/com/hypeboy/hypeBoard/service/UserService.java
> +        userRepository.save(user);
중복체크를 다른 메소드로 분리해서 작업한 것은 좋은 코드 습관같습니다~

이것은 저도 확신이 없어서 선생님과도 이야기를 나눠 보면 좋을 것 같은데,
우리가 id를 디비의 pk로 쓰고 있기 때문에 중복이 발생하면 디비가 throw를 던질 것이라고 생각이 됩니다.

저는 select를 한번 하고 등록을 하기보다는 insert를 시도하고 exception이 발생하는 것을 잡아서 처리하는 편이 좋다고 생각이 되긴하는데, 다음에 선생님과 이야기를 한번 나눠봐도 좋겠습니다!

2023-09-16 01:59 UTC, sonnbeom commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
확인했습니다!

2023-09-16 04:24 UTC, devsince2021 approved these changes
구두로 논의 후 새로 push 완료

2023-09-16 04:25 UTC, merged